### GET users without filters
GET {{baseUrl}}/api/user
Accept: application/json
Authorization: {{token}}

### GET users with filters
GET {{baseUrl}}/api/user?limit=10&username=john.doe
Accept: application/json
Authorization: {{token}}

### Get single user with roles
GET {{baseUrl}}/api/user/3
Accept: application/json
Authorization: {{token}}

### Create user with roles
POST {{baseUrl}}/api/user
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Jane Doe",
  "username": "jane.doe",
  "email": "jane.doe@example.com",
  "roles": [1, 2]
}

### Update user with roles
PUT {{baseUrl}}/api/user/1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Updated Name",
  "email": "updated.email@example.com",
  "is_active": true,
  "roles": [1]
}

### Update user without roles (won't change roles)
PUT {{baseUrl}}/api/user/3
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Updated Name Only",
  "email": "updated.email@example.com",
  "is_active": true
}

### Deactivate user
POST {{baseUrl}}/api/user/3/deactivate
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

### Activate user
POST {{baseUrl}}/api/user/3/activate
Content-Type: application/json
Accept: application/json
Authorization: {{token}}
